server:
  port: 9091


spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.7.207:8848
      config:
        server-addr: 121.36.7.207:8848
    #sentinel
    sentinel:
      transport:
        dashboard: localhost:8080

